export default defineNuxtConfig({
  modules: ['../src/module'],
  nuxtFortify: {
    baseUrl: 'http://localhost:80',
    authMode: 'cookie',
    features: {
      registration: true,
      resetPasswords: true,
      emailVerification: true,
      twoFactorAuthentication: true,
      updatePasswords: true,
    },
    tfaAfterLogin: true,
    endpoints: {
      csrf: '/sanctum/csrf-cookie',
      login: '/api/login',
      logout: '/api/logout',
      user: '/api/user',
      tfa: {
        enable: '/api/user/two-factor-authentication',
        disable: '/api/user/two-factor-authentication',
        code: '/api/user/two-factor-qr-code',
        recoveryCode: '/api/user/two-factor-recovery-codes',
        challenge: '/api/two-factor-challenge',
      },
      register: '/api/register',
      resetPassword: '/api/forgot-password',
      updatePassword: '/api/reset-password',
      confirmPassword: '/api/user/confirm-password',
      resendEmailVerificationLink: '/api/email/verification-notification',
    },
  },
  devtools: { enabled: true },
  compatibilityDate: '2024-07-14',
})
